methods:
    get: 3
    post: 6
    delete: 1
protocols:
    http: 8
    https: 2
fileExtensions:
    jpeg: 6
    mp3: 2
    xml: 2
codes:
	100: 6
	101: 1
	200: 3
	400: 3
ip:
	unique: 20

#  --min=24.01.2011 --max=07.02.2011